spring.application.name=finance-manager

# PostgreSQL Database Configuration (Supabase)
# Replace the below values with your Supabase database credentials
spring.datasource.url=jdbc:postgresql://db.fqvkszvtrgilluloecza.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Y@shJ@in1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Automatically create tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Prevent circular references in Jackson
spring.jackson.serialization.fail-on-empty-beans=false
